/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyPersonnelRouteImport } from './routes/my-personnel'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AircraftIndexRouteImport } from './routes/aircraft/index'
import { Route as AircraftCreateRouteImport } from './routes/aircraft/create'
import { Route as AreaIndexRouteImport } from './routes/area/index'
import { Route as InstructorDashboardIndexRouteImport } from './routes/instructor-dashboard/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as MissionsIndexRouteImport } from './routes/missions/index'
import { Route as PersonnelIndexRouteImport } from './routes/personnel/index'
import { Route as PersonnelCreateRouteImport } from './routes/personnel/create'
import { Route as SchedulesIndexRouteImport } from './routes/schedules/index'
import { Route as SchedulesIdRouteImport } from './routes/schedules/$id'
import { Route as SchedulesCreateRouteImport } from './routes/schedules/create'
import { Route as TraineeDashboardIndexRouteImport } from './routes/trainee-dashboard/index'
import { Route as TraineeDashboardIdRouteImport } from './routes/trainee-dashboard/$id'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersCreateRouteImport } from './routes/users/create'
import { Route as AircraftIdEditRouteImport } from './routes/aircraft/$id.edit'
import { Route as PersonnelIdEditRouteImport } from './routes/personnel/$id.edit'
import { Route as UsersIdEditRouteImport } from './routes/users/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPersonnelRoute = MyPersonnelRouteImport.update({
  id: '/my-personnel',
  path: '/my-personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftIndexRoute = AircraftIndexRouteImport.update({
  id: '/aircraft/',
  path: '/aircraft/',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftCreateRoute = AircraftCreateRouteImport.update({
  id: '/aircraft/create',
  path: '/aircraft/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaIndexRoute = AreaIndexRouteImport.update({
  id: '/area/',
  path: '/area/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorDashboardIndexRoute =
  InstructorDashboardIndexRouteImport.update({
    id: '/instructor-dashboard/',
    path: '/instructor-dashboard/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelIndexRoute = PersonnelIndexRouteImport.update({
  id: '/personnel/',
  path: '/personnel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelCreateRoute = PersonnelCreateRouteImport.update({
  id: '/personnel/create',
  path: '/personnel/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIndexRoute = SchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIdRoute = SchedulesIdRouteImport.update({
  id: '/schedules/$id',
  path: '/schedules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesCreateRoute = SchedulesCreateRouteImport.update({
  id: '/schedules/create',
  path: '/schedules/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeDashboardIndexRoute = TraineeDashboardIndexRouteImport.update({
  id: '/trainee-dashboard/',
  path: '/trainee-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeDashboardIdRoute = TraineeDashboardIdRouteImport.update({
  id: '/trainee-dashboard/$id',
  path: '/trainee-dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftIdEditRoute = AircraftIdEditRouteImport.update({
  id: '/aircraft/$id/edit',
  path: '/aircraft/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelIdEditRoute = PersonnelIdEditRouteImport.update({
  id: '/personnel/$id/edit',
  path: '/personnel/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdEditRoute = UsersIdEditRouteImport.update({
  id: '/users/$id/edit',
  path: '/users/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-personnel': typeof MyPersonnelRoute
  '/upload': typeof UploadRoute
  '/aircraft/create': typeof AircraftCreateRoute
  '/personnel/create': typeof PersonnelCreateRoute
  '/schedules/$id': typeof SchedulesIdRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/trainee-dashboard/$id': typeof TraineeDashboardIdRoute
  '/users/create': typeof UsersCreateRoute
  '/aircraft/': typeof AircraftIndexRoute
  '/area/': typeof AreaIndexRoute
  '/instructor-dashboard/': typeof InstructorDashboardIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/personnel/': typeof PersonnelIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/trainee-dashboard/': typeof TraineeDashboardIndexRoute
  '/users/': typeof UsersIndexRoute
  '/aircraft/$id/edit': typeof AircraftIdEditRoute
  '/personnel/$id/edit': typeof PersonnelIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-personnel': typeof MyPersonnelRoute
  '/upload': typeof UploadRoute
  '/aircraft/create': typeof AircraftCreateRoute
  '/personnel/create': typeof PersonnelCreateRoute
  '/schedules/$id': typeof SchedulesIdRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/trainee-dashboard/$id': typeof TraineeDashboardIdRoute
  '/users/create': typeof UsersCreateRoute
  '/aircraft': typeof AircraftIndexRoute
  '/area': typeof AreaIndexRoute
  '/instructor-dashboard': typeof InstructorDashboardIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/missions': typeof MissionsIndexRoute
  '/personnel': typeof PersonnelIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/trainee-dashboard': typeof TraineeDashboardIndexRoute
  '/users': typeof UsersIndexRoute
  '/aircraft/$id/edit': typeof AircraftIdEditRoute
  '/personnel/$id/edit': typeof PersonnelIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-personnel': typeof MyPersonnelRoute
  '/upload': typeof UploadRoute
  '/aircraft/create': typeof AircraftCreateRoute
  '/personnel/create': typeof PersonnelCreateRoute
  '/schedules/$id': typeof SchedulesIdRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/trainee-dashboard/$id': typeof TraineeDashboardIdRoute
  '/users/create': typeof UsersCreateRoute
  '/aircraft/': typeof AircraftIndexRoute
  '/area/': typeof AreaIndexRoute
  '/instructor-dashboard/': typeof InstructorDashboardIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/personnel/': typeof PersonnelIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/trainee-dashboard/': typeof TraineeDashboardIndexRoute
  '/users/': typeof UsersIndexRoute
  '/aircraft/$id/edit': typeof AircraftIdEditRoute
  '/personnel/$id/edit': typeof PersonnelIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my-personnel'
    | '/upload'
    | '/aircraft/create'
    | '/personnel/create'
    | '/schedules/$id'
    | '/schedules/create'
    | '/trainee-dashboard/$id'
    | '/users/create'
    | '/aircraft/'
    | '/area/'
    | '/instructor-dashboard/'
    | '/locations/'
    | '/missions/'
    | '/personnel/'
    | '/schedules/'
    | '/trainee-dashboard/'
    | '/users/'
    | '/aircraft/$id/edit'
    | '/personnel/$id/edit'
    | '/users/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-personnel'
    | '/upload'
    | '/aircraft/create'
    | '/personnel/create'
    | '/schedules/$id'
    | '/schedules/create'
    | '/trainee-dashboard/$id'
    | '/users/create'
    | '/aircraft'
    | '/area'
    | '/instructor-dashboard'
    | '/locations'
    | '/missions'
    | '/personnel'
    | '/schedules'
    | '/trainee-dashboard'
    | '/users'
    | '/aircraft/$id/edit'
    | '/personnel/$id/edit'
    | '/users/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my-personnel'
    | '/upload'
    | '/aircraft/create'
    | '/personnel/create'
    | '/schedules/$id'
    | '/schedules/create'
    | '/trainee-dashboard/$id'
    | '/users/create'
    | '/aircraft/'
    | '/area/'
    | '/instructor-dashboard/'
    | '/locations/'
    | '/missions/'
    | '/personnel/'
    | '/schedules/'
    | '/trainee-dashboard/'
    | '/users/'
    | '/aircraft/$id/edit'
    | '/personnel/$id/edit'
    | '/users/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyPersonnelRoute: typeof MyPersonnelRoute
  UploadRoute: typeof UploadRoute
  AircraftCreateRoute: typeof AircraftCreateRoute
  PersonnelCreateRoute: typeof PersonnelCreateRoute
  SchedulesIdRoute: typeof SchedulesIdRoute
  SchedulesCreateRoute: typeof SchedulesCreateRoute
  TraineeDashboardIdRoute: typeof TraineeDashboardIdRoute
  UsersCreateRoute: typeof UsersCreateRoute
  AircraftIndexRoute: typeof AircraftIndexRoute
  AreaIndexRoute: typeof AreaIndexRoute
  InstructorDashboardIndexRoute: typeof InstructorDashboardIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
  PersonnelIndexRoute: typeof PersonnelIndexRoute
  SchedulesIndexRoute: typeof SchedulesIndexRoute
  TraineeDashboardIndexRoute: typeof TraineeDashboardIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  AircraftIdEditRoute: typeof AircraftIdEditRoute
  PersonnelIdEditRoute: typeof PersonnelIdEditRoute
  UsersIdEditRoute: typeof UsersIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-personnel': {
      id: '/my-personnel'
      path: '/my-personnel'
      fullPath: '/my-personnel'
      preLoaderRoute: typeof MyPersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft/': {
      id: '/aircraft/'
      path: '/aircraft'
      fullPath: '/aircraft/'
      preLoaderRoute: typeof AircraftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft/create': {
      id: '/aircraft/create'
      path: '/aircraft/create'
      fullPath: '/aircraft/create'
      preLoaderRoute: typeof AircraftCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/': {
      id: '/area/'
      path: '/area'
      fullPath: '/area/'
      preLoaderRoute: typeof AreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor-dashboard/': {
      id: '/instructor-dashboard/'
      path: '/instructor-dashboard'
      fullPath: '/instructor-dashboard/'
      preLoaderRoute: typeof InstructorDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel/': {
      id: '/personnel/'
      path: '/personnel'
      fullPath: '/personnel/'
      preLoaderRoute: typeof PersonnelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel/create': {
      id: '/personnel/create'
      path: '/personnel/create'
      fullPath: '/personnel/create'
      preLoaderRoute: typeof PersonnelCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof SchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/$id': {
      id: '/schedules/$id'
      path: '/schedules/$id'
      fullPath: '/schedules/$id'
      preLoaderRoute: typeof SchedulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/create': {
      id: '/schedules/create'
      path: '/schedules/create'
      fullPath: '/schedules/create'
      preLoaderRoute: typeof SchedulesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee-dashboard/': {
      id: '/trainee-dashboard/'
      path: '/trainee-dashboard'
      fullPath: '/trainee-dashboard/'
      preLoaderRoute: typeof TraineeDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee-dashboard/$id': {
      id: '/trainee-dashboard/$id'
      path: '/trainee-dashboard/$id'
      fullPath: '/trainee-dashboard/$id'
      preLoaderRoute: typeof TraineeDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/create': {
      id: '/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft/$id/edit': {
      id: '/aircraft/$id/edit'
      path: '/aircraft/$id/edit'
      fullPath: '/aircraft/$id/edit'
      preLoaderRoute: typeof AircraftIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel/$id/edit': {
      id: '/personnel/$id/edit'
      path: '/personnel/$id/edit'
      fullPath: '/personnel/$id/edit'
      preLoaderRoute: typeof PersonnelIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id/edit': {
      id: '/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof UsersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyPersonnelRoute: MyPersonnelRoute,
  UploadRoute: UploadRoute,
  AircraftCreateRoute: AircraftCreateRoute,
  PersonnelCreateRoute: PersonnelCreateRoute,
  SchedulesIdRoute: SchedulesIdRoute,
  SchedulesCreateRoute: SchedulesCreateRoute,
  TraineeDashboardIdRoute: TraineeDashboardIdRoute,
  UsersCreateRoute: UsersCreateRoute,
  AircraftIndexRoute: AircraftIndexRoute,
  AreaIndexRoute: AreaIndexRoute,
  InstructorDashboardIndexRoute: InstructorDashboardIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
  PersonnelIndexRoute: PersonnelIndexRoute,
  SchedulesIndexRoute: SchedulesIndexRoute,
  TraineeDashboardIndexRoute: TraineeDashboardIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  AircraftIdEditRoute: AircraftIdEditRoute,
  PersonnelIdEditRoute: PersonnelIdEditRoute,
  UsersIdEditRoute: UsersIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
