/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaRouteRouteImport } from './routes/area/route'
import { Route as ComboxRouteImport } from './routes/combox'
import { Route as DateRouteImport } from './routes/date'
import { Route as FormGeneratorRouteImport } from './routes/form-generator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MulticheckRouteImport } from './routes/multicheck'
import { Route as MyPersonnelRouteImport } from './routes/my-personnel'
import { Route as TestRouteImport } from './routes/test'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AircraftIndexRouteImport } from './routes/aircraft/index'
import { Route as AreaIndexRouteImport } from './routes/area/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as GradingAttributeIndexRouteImport } from './routes/grading-attribute/index'
import { Route as GradingScaleIndexRouteImport } from './routes/grading-scale/index'
import { Route as GradingTemplateIndexRouteImport } from './routes/grading-template/index'
import { Route as InstructorDashboardIndexRouteImport } from './routes/instructor-dashboard/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as PersonnelIndexRouteImport } from './routes/personnel/index'
import { Route as PersonnelCreateRouteImport } from './routes/personnel/create'
import { Route as ReportsPrintScheduleRouteImport } from './routes/reports/print-schedule'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as RolesCreateRouteImport } from './routes/roles/create'
import { Route as SchedulesIndexRouteImport } from './routes/schedules/index'
import { Route as SchedulesCreateRouteImport } from './routes/schedules/create'
import { Route as SchedulesTimelineViewRouteImport } from './routes/schedules/timeline-view'
import { Route as TraineeDashboardIndexRouteImport } from './routes/trainee-dashboard/index'
import { Route as TraineeDashboardIdRouteImport } from './routes/trainee-dashboard/$id'
import { Route as TraineeDashboardCopyRouteImport } from './routes/trainee-dashboard/copy'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersCreateRouteImport } from './routes/users/create'
import { Route as PersonnelIdEditRouteImport } from './routes/personnel/$id.edit'
import { Route as RolesIdEditRouteImport } from './routes/roles/$id.edit'
import { Route as SchedulesIdEditRouteImport } from './routes/schedules/$id.edit'
import { Route as UsersIdEditRouteImport } from './routes/users/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRouteRoute = AreaRouteRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboxRoute = ComboxRouteImport.update({
  id: '/combox',
  path: '/combox',
  getParentRoute: () => rootRouteImport,
} as any)
const DateRoute = DateRouteImport.update({
  id: '/date',
  path: '/date',
  getParentRoute: () => rootRouteImport,
} as any)
const FormGeneratorRoute = FormGeneratorRouteImport.update({
  id: '/form-generator',
  path: '/form-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MulticheckRoute = MulticheckRouteImport.update({
  id: '/multicheck',
  path: '/multicheck',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPersonnelRoute = MyPersonnelRouteImport.update({
  id: '/my-personnel',
  path: '/my-personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftIndexRoute = AircraftIndexRouteImport.update({
  id: '/aircraft/',
  path: '/aircraft/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaIndexRoute = AreaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreaRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradingAttributeIndexRoute = GradingAttributeIndexRouteImport.update({
  id: '/grading-attribute/',
  path: '/grading-attribute/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradingScaleIndexRoute = GradingScaleIndexRouteImport.update({
  id: '/grading-scale/',
  path: '/grading-scale/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradingTemplateIndexRoute = GradingTemplateIndexRouteImport.update({
  id: '/grading-template/',
  path: '/grading-template/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorDashboardIndexRoute =
  InstructorDashboardIndexRouteImport.update({
    id: '/instructor-dashboard/',
    path: '/instructor-dashboard/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelIndexRoute = PersonnelIndexRouteImport.update({
  id: '/personnel/',
  path: '/personnel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelCreateRoute = PersonnelCreateRouteImport.update({
  id: '/personnel/create',
  path: '/personnel/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPrintScheduleRoute = ReportsPrintScheduleRouteImport.update({
  id: '/reports/print-schedule',
  path: '/reports/print-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesCreateRoute = RolesCreateRouteImport.update({
  id: '/roles/create',
  path: '/roles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIndexRoute = SchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesCreateRoute = SchedulesCreateRouteImport.update({
  id: '/schedules/create',
  path: '/schedules/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesTimelineViewRoute = SchedulesTimelineViewRouteImport.update({
  id: '/schedules/timeline-view',
  path: '/schedules/timeline-view',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeDashboardIndexRoute = TraineeDashboardIndexRouteImport.update({
  id: '/trainee-dashboard/',
  path: '/trainee-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeDashboardIdRoute = TraineeDashboardIdRouteImport.update({
  id: '/trainee-dashboard/$id',
  path: '/trainee-dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeDashboardCopyRoute = TraineeDashboardCopyRouteImport.update({
  id: '/trainee-dashboard/copy',
  path: '/trainee-dashboard/copy',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelIdEditRoute = PersonnelIdEditRouteImport.update({
  id: '/personnel/$id/edit',
  path: '/personnel/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdEditRoute = RolesIdEditRouteImport.update({
  id: '/roles/$id/edit',
  path: '/roles/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIdEditRoute = SchedulesIdEditRouteImport.update({
  id: '/schedules/$id/edit',
  path: '/schedules/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdEditRoute = UsersIdEditRouteImport.update({
  id: '/users/$id/edit',
  path: '/users/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area': typeof AreaRouteRouteWithChildren
  '/combox': typeof ComboxRoute
  '/date': typeof DateRoute
  '/form-generator': typeof FormGeneratorRoute
  '/login': typeof LoginRoute
  '/multicheck': typeof MulticheckRoute
  '/my-personnel': typeof MyPersonnelRoute
  '/test': typeof TestRoute
  '/upload': typeof UploadRoute
  '/personnel/create': typeof PersonnelCreateRoute
  '/reports/print-schedule': typeof ReportsPrintScheduleRoute
  '/roles/create': typeof RolesCreateRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/schedules/timeline-view': typeof SchedulesTimelineViewRoute
  '/trainee-dashboard/$id': typeof TraineeDashboardIdRoute
  '/trainee-dashboard/copy': typeof TraineeDashboardCopyRoute
  '/users/create': typeof UsersCreateRoute
  '/aircraft/': typeof AircraftIndexRoute
  '/area/': typeof AreaIndexRoute
  '/events/': typeof EventsIndexRoute
  '/grading-attribute/': typeof GradingAttributeIndexRoute
  '/grading-scale/': typeof GradingScaleIndexRoute
  '/grading-template/': typeof GradingTemplateIndexRoute
  '/instructor-dashboard/': typeof InstructorDashboardIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/personnel/': typeof PersonnelIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/trainee-dashboard/': typeof TraineeDashboardIndexRoute
  '/users/': typeof UsersIndexRoute
  '/personnel/$id/edit': typeof PersonnelIdEditRoute
  '/roles/$id/edit': typeof RolesIdEditRoute
  '/schedules/$id/edit': typeof SchedulesIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combox': typeof ComboxRoute
  '/date': typeof DateRoute
  '/form-generator': typeof FormGeneratorRoute
  '/login': typeof LoginRoute
  '/multicheck': typeof MulticheckRoute
  '/my-personnel': typeof MyPersonnelRoute
  '/test': typeof TestRoute
  '/upload': typeof UploadRoute
  '/personnel/create': typeof PersonnelCreateRoute
  '/reports/print-schedule': typeof ReportsPrintScheduleRoute
  '/roles/create': typeof RolesCreateRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/schedules/timeline-view': typeof SchedulesTimelineViewRoute
  '/trainee-dashboard/$id': typeof TraineeDashboardIdRoute
  '/trainee-dashboard/copy': typeof TraineeDashboardCopyRoute
  '/users/create': typeof UsersCreateRoute
  '/aircraft': typeof AircraftIndexRoute
  '/area': typeof AreaIndexRoute
  '/events': typeof EventsIndexRoute
  '/grading-attribute': typeof GradingAttributeIndexRoute
  '/grading-scale': typeof GradingScaleIndexRoute
  '/grading-template': typeof GradingTemplateIndexRoute
  '/instructor-dashboard': typeof InstructorDashboardIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/personnel': typeof PersonnelIndexRoute
  '/roles': typeof RolesIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/trainee-dashboard': typeof TraineeDashboardIndexRoute
  '/users': typeof UsersIndexRoute
  '/personnel/$id/edit': typeof PersonnelIdEditRoute
  '/roles/$id/edit': typeof RolesIdEditRoute
  '/schedules/$id/edit': typeof SchedulesIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area': typeof AreaRouteRouteWithChildren
  '/combox': typeof ComboxRoute
  '/date': typeof DateRoute
  '/form-generator': typeof FormGeneratorRoute
  '/login': typeof LoginRoute
  '/multicheck': typeof MulticheckRoute
  '/my-personnel': typeof MyPersonnelRoute
  '/test': typeof TestRoute
  '/upload': typeof UploadRoute
  '/personnel/create': typeof PersonnelCreateRoute
  '/reports/print-schedule': typeof ReportsPrintScheduleRoute
  '/roles/create': typeof RolesCreateRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/schedules/timeline-view': typeof SchedulesTimelineViewRoute
  '/trainee-dashboard/$id': typeof TraineeDashboardIdRoute
  '/trainee-dashboard/copy': typeof TraineeDashboardCopyRoute
  '/users/create': typeof UsersCreateRoute
  '/aircraft/': typeof AircraftIndexRoute
  '/area/': typeof AreaIndexRoute
  '/events/': typeof EventsIndexRoute
  '/grading-attribute/': typeof GradingAttributeIndexRoute
  '/grading-scale/': typeof GradingScaleIndexRoute
  '/grading-template/': typeof GradingTemplateIndexRoute
  '/instructor-dashboard/': typeof InstructorDashboardIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/personnel/': typeof PersonnelIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/trainee-dashboard/': typeof TraineeDashboardIndexRoute
  '/users/': typeof UsersIndexRoute
  '/personnel/$id/edit': typeof PersonnelIdEditRoute
  '/roles/$id/edit': typeof RolesIdEditRoute
  '/schedules/$id/edit': typeof SchedulesIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area'
    | '/combox'
    | '/date'
    | '/form-generator'
    | '/login'
    | '/multicheck'
    | '/my-personnel'
    | '/test'
    | '/upload'
    | '/personnel/create'
    | '/reports/print-schedule'
    | '/roles/create'
    | '/schedules/create'
    | '/schedules/timeline-view'
    | '/trainee-dashboard/$id'
    | '/trainee-dashboard/copy'
    | '/users/create'
    | '/aircraft/'
    | '/area/'
    | '/events/'
    | '/grading-attribute/'
    | '/grading-scale/'
    | '/grading-template/'
    | '/instructor-dashboard/'
    | '/locations/'
    | '/personnel/'
    | '/roles/'
    | '/schedules/'
    | '/trainee-dashboard/'
    | '/users/'
    | '/personnel/$id/edit'
    | '/roles/$id/edit'
    | '/schedules/$id/edit'
    | '/users/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combox'
    | '/date'
    | '/form-generator'
    | '/login'
    | '/multicheck'
    | '/my-personnel'
    | '/test'
    | '/upload'
    | '/personnel/create'
    | '/reports/print-schedule'
    | '/roles/create'
    | '/schedules/create'
    | '/schedules/timeline-view'
    | '/trainee-dashboard/$id'
    | '/trainee-dashboard/copy'
    | '/users/create'
    | '/aircraft'
    | '/area'
    | '/events'
    | '/grading-attribute'
    | '/grading-scale'
    | '/grading-template'
    | '/instructor-dashboard'
    | '/locations'
    | '/personnel'
    | '/roles'
    | '/schedules'
    | '/trainee-dashboard'
    | '/users'
    | '/personnel/$id/edit'
    | '/roles/$id/edit'
    | '/schedules/$id/edit'
    | '/users/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/area'
    | '/combox'
    | '/date'
    | '/form-generator'
    | '/login'
    | '/multicheck'
    | '/my-personnel'
    | '/test'
    | '/upload'
    | '/personnel/create'
    | '/reports/print-schedule'
    | '/roles/create'
    | '/schedules/create'
    | '/schedules/timeline-view'
    | '/trainee-dashboard/$id'
    | '/trainee-dashboard/copy'
    | '/users/create'
    | '/aircraft/'
    | '/area/'
    | '/events/'
    | '/grading-attribute/'
    | '/grading-scale/'
    | '/grading-template/'
    | '/instructor-dashboard/'
    | '/locations/'
    | '/personnel/'
    | '/roles/'
    | '/schedules/'
    | '/trainee-dashboard/'
    | '/users/'
    | '/personnel/$id/edit'
    | '/roles/$id/edit'
    | '/schedules/$id/edit'
    | '/users/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaRouteRoute: typeof AreaRouteRouteWithChildren
  ComboxRoute: typeof ComboxRoute
  DateRoute: typeof DateRoute
  FormGeneratorRoute: typeof FormGeneratorRoute
  LoginRoute: typeof LoginRoute
  MulticheckRoute: typeof MulticheckRoute
  MyPersonnelRoute: typeof MyPersonnelRoute
  TestRoute: typeof TestRoute
  UploadRoute: typeof UploadRoute
  PersonnelCreateRoute: typeof PersonnelCreateRoute
  ReportsPrintScheduleRoute: typeof ReportsPrintScheduleRoute
  RolesCreateRoute: typeof RolesCreateRoute
  SchedulesCreateRoute: typeof SchedulesCreateRoute
  SchedulesTimelineViewRoute: typeof SchedulesTimelineViewRoute
  TraineeDashboardIdRoute: typeof TraineeDashboardIdRoute
  TraineeDashboardCopyRoute: typeof TraineeDashboardCopyRoute
  UsersCreateRoute: typeof UsersCreateRoute
  AircraftIndexRoute: typeof AircraftIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GradingAttributeIndexRoute: typeof GradingAttributeIndexRoute
  GradingScaleIndexRoute: typeof GradingScaleIndexRoute
  GradingTemplateIndexRoute: typeof GradingTemplateIndexRoute
  InstructorDashboardIndexRoute: typeof InstructorDashboardIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PersonnelIndexRoute: typeof PersonnelIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  SchedulesIndexRoute: typeof SchedulesIndexRoute
  TraineeDashboardIndexRoute: typeof TraineeDashboardIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PersonnelIdEditRoute: typeof PersonnelIdEditRoute
  RolesIdEditRoute: typeof RolesIdEditRoute
  SchedulesIdEditRoute: typeof SchedulesIdEditRoute
  UsersIdEditRoute: typeof UsersIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area': {
      id: '/area'
      path: '/area'
      fullPath: '/area'
      preLoaderRoute: typeof AreaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combox': {
      id: '/combox'
      path: '/combox'
      fullPath: '/combox'
      preLoaderRoute: typeof ComboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date': {
      id: '/date'
      path: '/date'
      fullPath: '/date'
      preLoaderRoute: typeof DateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-generator': {
      id: '/form-generator'
      path: '/form-generator'
      fullPath: '/form-generator'
      preLoaderRoute: typeof FormGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multicheck': {
      id: '/multicheck'
      path: '/multicheck'
      fullPath: '/multicheck'
      preLoaderRoute: typeof MulticheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-personnel': {
      id: '/my-personnel'
      path: '/my-personnel'
      fullPath: '/my-personnel'
      preLoaderRoute: typeof MyPersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft/': {
      id: '/aircraft/'
      path: '/aircraft'
      fullPath: '/aircraft/'
      preLoaderRoute: typeof AircraftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/': {
      id: '/area/'
      path: '/'
      fullPath: '/area/'
      preLoaderRoute: typeof AreaIndexRouteImport
      parentRoute: typeof AreaRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grading-attribute/': {
      id: '/grading-attribute/'
      path: '/grading-attribute'
      fullPath: '/grading-attribute/'
      preLoaderRoute: typeof GradingAttributeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grading-scale/': {
      id: '/grading-scale/'
      path: '/grading-scale'
      fullPath: '/grading-scale/'
      preLoaderRoute: typeof GradingScaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grading-template/': {
      id: '/grading-template/'
      path: '/grading-template'
      fullPath: '/grading-template/'
      preLoaderRoute: typeof GradingTemplateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor-dashboard/': {
      id: '/instructor-dashboard/'
      path: '/instructor-dashboard'
      fullPath: '/instructor-dashboard/'
      preLoaderRoute: typeof InstructorDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel/': {
      id: '/personnel/'
      path: '/personnel'
      fullPath: '/personnel/'
      preLoaderRoute: typeof PersonnelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel/create': {
      id: '/personnel/create'
      path: '/personnel/create'
      fullPath: '/personnel/create'
      preLoaderRoute: typeof PersonnelCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/print-schedule': {
      id: '/reports/print-schedule'
      path: '/reports/print-schedule'
      fullPath: '/reports/print-schedule'
      preLoaderRoute: typeof ReportsPrintScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/create': {
      id: '/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof RolesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof SchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/create': {
      id: '/schedules/create'
      path: '/schedules/create'
      fullPath: '/schedules/create'
      preLoaderRoute: typeof SchedulesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/timeline-view': {
      id: '/schedules/timeline-view'
      path: '/schedules/timeline-view'
      fullPath: '/schedules/timeline-view'
      preLoaderRoute: typeof SchedulesTimelineViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee-dashboard/': {
      id: '/trainee-dashboard/'
      path: '/trainee-dashboard'
      fullPath: '/trainee-dashboard/'
      preLoaderRoute: typeof TraineeDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee-dashboard/$id': {
      id: '/trainee-dashboard/$id'
      path: '/trainee-dashboard/$id'
      fullPath: '/trainee-dashboard/$id'
      preLoaderRoute: typeof TraineeDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee-dashboard/copy': {
      id: '/trainee-dashboard/copy'
      path: '/trainee-dashboard/copy'
      fullPath: '/trainee-dashboard/copy'
      preLoaderRoute: typeof TraineeDashboardCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/create': {
      id: '/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel/$id/edit': {
      id: '/personnel/$id/edit'
      path: '/personnel/$id/edit'
      fullPath: '/personnel/$id/edit'
      preLoaderRoute: typeof PersonnelIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$id/edit': {
      id: '/roles/$id/edit'
      path: '/roles/$id/edit'
      fullPath: '/roles/$id/edit'
      preLoaderRoute: typeof RolesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/$id/edit': {
      id: '/schedules/$id/edit'
      path: '/schedules/$id/edit'
      fullPath: '/schedules/$id/edit'
      preLoaderRoute: typeof SchedulesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id/edit': {
      id: '/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof UsersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AreaRouteRouteChildren {
  AreaIndexRoute: typeof AreaIndexRoute
}

const AreaRouteRouteChildren: AreaRouteRouteChildren = {
  AreaIndexRoute: AreaIndexRoute,
}

const AreaRouteRouteWithChildren = AreaRouteRoute._addFileChildren(
  AreaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaRouteRoute: AreaRouteRouteWithChildren,
  ComboxRoute: ComboxRoute,
  DateRoute: DateRoute,
  FormGeneratorRoute: FormGeneratorRoute,
  LoginRoute: LoginRoute,
  MulticheckRoute: MulticheckRoute,
  MyPersonnelRoute: MyPersonnelRoute,
  TestRoute: TestRoute,
  UploadRoute: UploadRoute,
  PersonnelCreateRoute: PersonnelCreateRoute,
  ReportsPrintScheduleRoute: ReportsPrintScheduleRoute,
  RolesCreateRoute: RolesCreateRoute,
  SchedulesCreateRoute: SchedulesCreateRoute,
  SchedulesTimelineViewRoute: SchedulesTimelineViewRoute,
  TraineeDashboardIdRoute: TraineeDashboardIdRoute,
  TraineeDashboardCopyRoute: TraineeDashboardCopyRoute,
  UsersCreateRoute: UsersCreateRoute,
  AircraftIndexRoute: AircraftIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  GradingAttributeIndexRoute: GradingAttributeIndexRoute,
  GradingScaleIndexRoute: GradingScaleIndexRoute,
  GradingTemplateIndexRoute: GradingTemplateIndexRoute,
  InstructorDashboardIndexRoute: InstructorDashboardIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PersonnelIndexRoute: PersonnelIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  SchedulesIndexRoute: SchedulesIndexRoute,
  TraineeDashboardIndexRoute: TraineeDashboardIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PersonnelIdEditRoute: PersonnelIdEditRoute,
  RolesIdEditRoute: RolesIdEditRoute,
  SchedulesIdEditRoute: SchedulesIdEditRoute,
  UsersIdEditRoute: UsersIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
