import { useRef, useState } from 'react'
import type {
  GradingScaleFormData,
  GradingScaleOptionFormData,
} from './grading-scale-form'
import { toast } from 'react-hot-toast'
import { Button } from '@/components/ui/button'
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from '@/components/ui/table'
import { PencilIcon, PlusIcon, SaveIcon, TrashIcon, XIcon } from 'lucide-react'
import { baseFormOptions, useAppForm } from '@/components/form/tanstack-form'
import { z } from 'zod'
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import { required } from '@/routes/schedules/-components/shedule-form'
import { generateGradeRanges } from './utils'

export function ScaleOptionsLine({
  options,
  setOptions,
}: {
  options: GradingScaleFormData['options']
  setOptions: (options: GradingScaleFormData['options']) => void
}) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [editingIndex, setEditingIndex] = useState<number | null>(null)
  const [autoGeneratedRange, setAutoGeneratedRange] = useState(false)
  const saveOption = (data: GradingScaleOptionFormData) => {
    const hasDuplicateLabel = options.some(
      (option, index) =>
        index !== editingIndex &&
        option.label.toLowerCase() === data.label.toLowerCase(),
    )

    if (hasDuplicateLabel) {
      toast.error('Option name already used')
      return false
    }

    let next =
      editingIndex === null
        ? [...options, data]
        : options.map((item, index) => (index === editingIndex ? data : item))

    if (autoGeneratedRange) {
      next = generateGradeRanges(next)
    }

    next = next.sort((a, b) => b.point - a.point)
    setEditingIndex(null)
    setOptions(next)
    return true
  }

  const handleDeleteOption = (index: number) => {
    const next = options.filter((_, optionIndex) => optionIndex !== index)
    // setOptions(generateGradeRanges(next))
    setOptions(next)
    setEditingIndex(null)
  }

  return (
    <div className="space-y-3">
      <div className="text-sm font-semibold text-muted-foreground border-b pb-2 flex items-center justify-between">
        Options
        <div className="flex items-center gap-2">
          <Checkbox
            id="auto-generated-range"
            checked={autoGeneratedRange}
            onCheckedChange={setAutoGeneratedRange}
          />
          <Label htmlFor="auto-generated-range">Auto-generated range</Label>
        </div>
      </div>
      <ScaleOptionForm
        items={options}
        inputRef={inputRef}
        key={editingIndex ?? 'new'}
        initialFormData={
          editingIndex !== null ? options[editingIndex] : undefined
        }
        isEditing={editingIndex !== null}
        onSave={saveOption}
        onCancel={() => setEditingIndex(null)}
        editingIndex={editingIndex ?? undefined}
        autoGeneratedRange={autoGeneratedRange}
      />
      <div className="overflow-hidden rounded-md border">
        {options.length > 0 ? (
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/40">
                {/* <TableHead className="w-12 text-center">#</TableHead> */}
                <TableHead>Name</TableHead>
                <TableHead>Range</TableHead>
                <TableHead>Point</TableHead>
                <TableHead className="w-20 text-center">-</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {options.map((option, index) => (
                <TableRow
                  key={`${option.label}-${index}`}
                  className="even:bg-muted/30"
                >
                  <TableCell>{option.label}</TableCell>
                  <TableCell>
                    {option.lowerBound} – {option.upperBound}
                  </TableCell>
                  <TableCell>{option.point}</TableCell>
                  <TableCell>
                    <div className="flex justify-center gap-1">
                      <Button
                        type="button"
                        size="icon-sm"
                        variant="ghost"
                        onClick={() => {
                          setEditingIndex(index)
                          inputRef.current?.focus()
                        }}
                      >
                        <PencilIcon className="size-4" />
                      </Button>
                      <Button
                        type="button"
                        size="icon-sm"
                        variant="ghost"
                        onClick={() => handleDeleteOption(index)}
                      >
                        <TrashIcon className="size-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : (
          <div className="px-4 py-8 text-center text-sm text-muted-foreground">
            No options added yet
          </div>
        )}
      </div>
    </div>
  )
}

function ScaleOptionForm({
  inputRef,
  initialFormData,
  isEditing,
  onSave,
  onCancel,
  items,
  autoGeneratedRange,
  editingIndex,
}: {
  inputRef: React.RefObject<HTMLInputElement | null>
  initialFormData?: GradingScaleOptionFormData
  isEditing: boolean
  onSave: (data: GradingScaleOptionFormData) => boolean
  onCancel: () => void
  items: GradingScaleOptionFormData[]
  autoGeneratedRange?: boolean
  editingIndex?: number
}) {
  const form = useAppForm({
    ...baseFormOptions,
    defaultValues: initialFormData,
    onSubmit: (data) => {
      const conflictingRange = findConflictingRange(
        items,
        data.value,
        editingIndex,
      )
      if (conflictingRange) {
        toast.error(
          `Range ${conflictingRange.label} conflicts with  ${data.value.label} Range`,
        )
        return
      }
      inputRef.current?.focus()
      form.reset()
      onSave({ ...data.value, point: data.value.upperBound })
    },
  })

  const handleCancel = () => {
    onCancel()
  }

  return (
    <>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          form.handleSubmit()
        }}
      >
        <div className="flex items-start gap-3">
          <form.AppField
            name="label"
            validators={{
              onDynamic: ({ value }) => required(value),
            }}
            children={(f) => (
              <f.CTextField label="Label" placeholder="(eg. A,B)" required />
            )}
          />

          <form.AppField
            name="lowerBound"
            validators={{
              onDynamic({ value }) {
                if (autoGeneratedRange) return undefined
                // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
                if (value === null) return 'Required'
                if (value < 0) return 'Must be greater than 0'
                if (value > 100) return 'Must be less than 100'
                return undefined
              },
            }}
            children={(f) => (
              <f.CTextField
                disabled={autoGeneratedRange}
                type="number"
                label="Lower Bound"
                required
                valueAsNumber
              />
            )}
          />

          <form.AppField
            name="upperBound"
            validators={{
              onDynamic({ value }) {
                if (autoGeneratedRange) return undefined
                // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
                if (value === null) return 'Required'
                if (value < 0) return 'Must be greater than 0'
                if (value > 100) return 'Must be less than 100'
                if (value < form.state.values.lowerBound) {
                  return 'Must be greater than lower bound'
                }
                return undefined
              },
            }}
            children={(f) => (
              <f.CTextField
                disabled={autoGeneratedRange}
                type="number"
                label="Upper Bound"
                required
                valueAsNumber
              />
            )}
          />

          <form.Subscribe
            selector={(state) => state.isValid}
            children={() => (
              <Button
                className=" mt-auto border"
                type="submit"
                variant="secondary"
              >
                {isEditing ? <SaveIcon /> : <PlusIcon />}
              </Button>
            )}
          />

          {isEditing && (
            <Button
              type="button"
              variant="secondary"
              className="mt-auto"
              onClick={() => handleCancel()}
            >
              <XIcon className="size-4" />
            </Button>
          )}
        </div>
      </form>
      <p className="text-xs text-muted-foreground">
        Range and point are based on option order, with a total of 100. The
        first option is the highest grade, e.g. A=100, B=75, C=50, F=25. Both
        bounds are inclusive.
      </p>
    </>
  )
}

function findConflictingRange(
  ranges: GradingScaleOptionFormData[],
  newRange: GradingScaleOptionFormData,
  excludeIndex?: number,
): GradingScaleOptionFormData | undefined {
  return ranges.find((range, index) => {
    // Don't compare the option against itself while editing
    if (excludeIndex != null && index === excludeIndex) {
      return false
    }

    return (
      newRange.lowerBound <= range.upperBound &&
      newRange.upperBound >= range.lowerBound
    )
  })
}
